apiVersion: apps/v1
kind: Deployment
metadata:
  name: makemkv
  labels:
    app: makemkv
spec:
  selector:
    matchLabels:
      app: makemkv
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: makemkv
    spec:
      containers:
      - name: makemkv
        image: jlesage/makemkv:latest
        volumeMounts:
        - mountPath: /storage/
          name: storage
        - mountPath: /config/
          name: config
        - mountPath: /output/
          name: output
        - mountPath: /dev/sg1
          name: sg1
        - mountPath: /dev/sr0
          name: sr0
        ports:
        - containerPort: 5800
          name: gui
      volumes:
      - name: storage
        hostPath:
          path: /storage/makemkv/storage/
      - name: config
        hostPath:
          path: /srv/makemkv/
      - name: output
        hostPath:
          path: /storage/makemkv/output/
      - name: sg1
        hostPath:
          path: /dev/sg1
      - name: sr0
        hostPath:
          path: /dev/sr0

---

apiVersion: v1
kind: Service
metadata:
  name: makemkv-gui
spec:
  selector:
    app: makemkv
  type: NodePort
  ports:
  - name: makemkv-gui
    nodePort: 30025
    port: 30025
    targetPort: gui