apiVersion: v1
kind: Service
metadata:
 name: beets
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8337
  selector:
    app: beets

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: beets
  name: beets
spec:
  selector:
    matchLabels:
      app: beets
  replicas: 1
  template:
    metadata:
      labels:
        app: beets
    spec:
      containers:
      - image: linuxserver/beets:latest
        imagePullPolicy: Always
        name: beets
        volumeMounts:
          - mountPath: /music/
            name: beets
          - mountPath: /config/
            name: config
      - image: minio/mc:latest
        name: minio
        args: ["mirror", "--watch", "--overwrite", "/music/", "minio/music/"]
        volumeMounts:
        - mountPath: /music/
          name: beets
          readOnly: true
        - mountPath: /root/.mc/config.json
          name: mc-config
          subPath: config.json
      volumes:
        - name: beets
          persistentVolumeClaim:
            claimName: beets-pvc
        - name: config
          configMap:
            name: beets-config
        - name: mc-config
          configMap:
            name: beets-mc-config

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beets-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 150Gi
  storageClassName: rook-ceph-block

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: beets-mc-config
  labels:
    app: beets
data:
  config.json: |
    {
      "version": "9",
      "hosts": {
        "minio": {
          "url": "http://192.168.1.69:30004",
          "accessKey": "AKIAIOSFODNN7EXAMPLE",
          "secretKey": "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY",
          "api": "s3v4",
          "lookup": "auto"
        }
      }
    }


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: beets-config
  labels:
    app: beets
data:
  config.yaml: |
    plugins: fetchart scrub chroma web missing info export
    directory: /music
    library: /music/library.db
    art_filename: albumart
    threaded: yes
    original_date: no
    per_disc_numbering: no
        
    paths:
        default: $albumartist/$album [$media, $format, $bitdepth-$samplerate] ($mb_albumid)/Disk $disc/$track $title ($length)
        singleton: $albumartist/$album [$media, $format, $bitdepth-$samplerate] ($mb_albumid)/$track $title ($length)
        comp: Compilations/$album [$media, $format, $bitdepth-$samplerate] ($mb_albumid)/Disk $disc/$track $title ($length)
    
    import:
        write: yes
        copy: no
        move: yes
        resume: ask
        incremental: yes
        quiet_fallback: skip
        timid: yes
        log: /music/beet.log

    fetchart:
        auto: yes

    scrub:
        auto: yes

    replace:
        '^\.': _
        '[\x00-\x1f]': _
        '[<>:"\?\*\|]': _
        '[\xE8-\xEB]': e
        '[\xEC-\xEF]': i
        '[\xE2-\xE6]': a
        '[\xF2-\xF6]': o
        '[\xF8]': o
        '\.$': _
        '\s+$': ''

    web:
        host: 0.0.0.0
        port: 8337
