apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:latest
          volumeMounts:
            - mountPath: /etc/gitlab/
              name: gitlab-config
            - mountPath: /var/log/gitlab/
              name: gitlab-logs
            - mountPath: /var/opt/gitlab/
              name: gitlab-data
      volumes:
      - name: gitlab-config
        hostPath:
          path: /srv/gitlab/config/
      - name: gitlab-logs
        hostPath:
          path: /srv/gitlab/logs/
      - name: gitlab-data
        hostPath:
          path: /srv/gitlab/data/
---

apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  labels:
    app: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
  - name: http
    nodePort: 30420
    port: 80
  - name: https
    nodePort: 30421
    port: 443
