apiVersion: apps/v1
kind: Deployment
metadata:
  name: duplicati
  labels:
    app: duplicati
spec:
  selector:
    matchLabels:
      app: duplicati
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: duplicati
    spec:
      containers:
      - name: duplicati
        image: linuxserver/duplicati:latest
        volumeMounts:
        - mountPath: /backup/storage/
          name: storage
        - mountPath: /backup/srv/
          name: srv
        - mountPath: /config/
          name: config
      volumes:
      - name: storage
        hostPath:
          path: /storage/
      - name: srv
        hostPath:
          path: /srv/
      - name: config
        hostPath:
          path: /srv/duplicati/

---

apiVersion: v1
kind: Service
metadata:
  name: duplicati-server
spec:
  selector:
    app: duplicati
  type: NodePort
  ports:
  - name: duplicati-web
    nodePort: 30024
    port: 30024
    targetPort: 8200