apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.9.2
        env:
        - name: RUN_MODE
          value: dev
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: DB_TYPE
          value: mysql
        - name: DB_HOST
          value: mariadb.gitea.svc.cluster.local:3306
        - name: DB_NAME
          value: gitea
        - name: DB_USER
          value: root
        - name: DB_PASSWD
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: mariadb-password
        - name: LFS_START_SERVER
          value: "true"
        - name: ROOT_URL
          value: http://192.168.1.69:31000/
        - name: SSH_DOMAIN
          value: 192.168.1.69:30022
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 22
          name: git-ssh
        volumeMounts:
        - mountPath: /data
          name: git-data
      volumes:
      - name: git-data
        hostPath:
          path: /storage/gitea/

---

apiVersion: v1
kind: Service
metadata:
  name: gitea
spec:
  selector:
    app: gitea
  type: NodePort
  ports:
  - name: gitea-http
    nodePort: 31000
    port: 31000
    targetPort: http
  - name: gitea-ssh
    nodePort: 30022
    port: 30022
    targetPort: gitea-ssh

---

apiVersion: v1
kind: Secret
metadata:
  name: gitea-secrets
type: Opaque
data:
  mariadb-password: dnNnI0JzNV00aGdAeCxFPAo=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
data:
  mariadb-user: root
  