apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  labels:
    app: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.9.2
        env:
        - name: RUN_MODE
          value: dev
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: postgres.gitea.svc.cluster.local:5432
        - name: DB_NAME
          value: gitea
        - name: DB_USER
          value: gitea
        - name: DB_PASSWD
          value: gitea
        - name: LFS_START_SERVER
          value: "true"
        - name: ROOT_URL
          value: http://192.168.1.69:31000/
        - name: SSH_DOMAIN
          value: 192.168.1.69:30022
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 22
          name: git-ssh
        volumeMounts:
        - mountPath: /data
          name: git-data
      volumes:
      - name: git-data
        hostPath:
          path: /srv/gitea/data/

---

kind: Service
apiVersion: v1
metadata:
  name: gitea
spec:
  selector:
    app: gitea
  type: NodePort
  ports:
  - name: gitea-http
    nodePort: 31000
    port: 80
    targetPort: http
  - name: gitea-ssh
    nodePort: 30022
    port: 22
    targetPort: gitea-ssh