apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb/server:10.4
        name: mariadb
        env:
          # TODO: Use secrets instead
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-secrets
              key: mariadb-password
        - name: MARIADB_USER
          value: gitea
        - name: MARIADB_USER
          value: gitea
        - name: MYSQL_TCP_PORT
          value: 3306
        ports:
        - containerPort: 3306
          name: mariadbtcp
        volumeMounts:
        - name: gitea-mariadb-data
          mountPath: /var/lib/mysql/
      volumes:
      - name: gitea-mariadb-data
        hostPath:
          path: /srv/gitea/mariadb/

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
  name: mariadb
spec:
  type: ClusterIP
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb