apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app: nextcloud
spec:
  selector:
    matchLabels:
      app: nextcloud
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:latest
          env:
          - name: MYSQL_DATABASE
            value: nextcloud
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nextcloud-secrets
                key: mariadb-password
          - name: MYSQL_HOST
            value: mariadb.nextcloud.svc.cluster.local:3306 
          # ports:
          # - containerPort: 80
          #   name: http
          volumeMounts:
          - mountPath: /var/www/html/
            name: nextcloud-main
          - mountPath: /var/www/html/data
            name: nextcloud-data
          - mountPath: /var/www/html/custom_apps
            name: nextcloud-custom-apps
          - mountPath: /var/www/html/config
            name: nextcloud-config
          - mountPath: /var/www/html/themes/
            name: nextcloud-themes
      volumes:
      - name: nextcloud-main
        hostPath:
          path: /srv/nextcloud/main/
      - name: nextcloud-data
        hostPath:
          path: /storage/nextcloud/data/
      - name: nextcloud-custom-apps
        hostPath:
          path: /storage/nextcloud/custom_apps/
      - name: nextcloud-config
        hostPath:
          path: /srv/nextcloud/config/
      - name: nextcloud-themes
        hostPath:
          path: /srv/nextcloud/themes/

---

apiVersion: v1
kind: Service
metadata:
  name: nextcloud
spec:
  selector:
    app: nextcloud
  type: NodePort
  ports:
  - name: nextcloud-http
    nodePort: 31004
    port: 8081
    targetPort: 80

---

apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-secrets
type: Opaque
data:
  mariadb-password: dnNnI0JzNV00aGdAeCxFPAo=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-config
data:
  mariadb-user: nextcloud
  