apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: server
          image: itzg/minecraft-server:latest
          env:
          - name: EULA
            value: "TRUE"
          - name: SERVER_PORT
            value: {{ .Values.port | quote }}
